### ISSUE TITLE
[FEAT] 현재 사용중인 Profile 정보를 관리한다.

### ISSUE THREAD

**Issue by lcqff** [BDD-CLUB/2024-2-untitled-music-back#16]
## 💬 기능 내용

서버는 Artist가 지금 어떤 Profile을 사용중인지 알수 있어야 합니다.
~~토큰에 profile 정보를 함께 담아 보내도록 합시다.~~

access_token과는 별개의 cookie에 profile uuid를 저장하도록 합니다.
profile 선택 정보 자체는 사용자 인증과는 관계없고, 사용자 인증에 비해 변경 빈도가 높으므로 access_token과 분리된 cookie에 저장합니다.
uuid 정보는 조작 가능성이 낮으므로 따로 암호화할 계획은 없습니다.

## 📝 작업 내용

- [ ] 로그인시 쿠키에 기본 profile 정보를 저장한다.
- [ ] profile 변경시 쿠키를 교체한다.
- [ ] 쿠키를 통한 profile을 조회한다.
- [ ] 쿠키가 존재하지 않을시 사용자의 main profile을 쿠키에 저장 및 조회한다.

**Comment by amm0124** [comment]
확인했습니다!
